name: Test Coverage
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1

    - name: Run tests
      run: |
        pip install -r requirements.txt
        coverage run -m pytest

    - name: Upload coverage data to coveralls.io
      env:
        GITHUB_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        COVERALLS_PARALLEL: true
      run: coveralls debug --service=github
